### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by echo-che** [qinenergy/DA-diagnosis#1]
Hello! how to download data, can you provide the ".npy" file . Thank you very much.

**Comment by qinenergy** [comment]
Data is available here:
https://github.com/qinenergy/DA-diagnosis/releases/tag/data

You can directly use the code in CodaLab:
https://colab.research.google.com/drive/17oQvdI41wxBWU8zZInfvGzD-YJyGdLLl?usp=sharing
